# Site settings
name: 666
subtitile: tai 6
author: yang 6
# baseurl: "" # the subpath of your site, e.g. blog/
baseurl: "/"
description: >
  Notes on the basics of quantum information
banner: Information is physical
cover: "_assets/header/header_image.jpg"
short_icon: "/assets/logo/favicon.ico"
icon: "/assets/logo/logo.png"
figure_url: "/assets/images/"
about: "about/"

# sass:
#   sass_dir: _sass

permalink: :categories/:title/
# permalink: /:year/:month/:day/:title/
# paginate: 10

collections:

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

# resume_site: "https://WXMpublic.github.io/Blog/about/"
github: "https://github.com/WXMpublic/"

# Build settings
# markdown: kramdown